services:
  redis:
    build: .
    ports:
      - 6379:6379
      - 6380:6380
  builder:
    image: ubuntu:22.04
    container_name: builder
    tty: true
    environment:
      - BOOST_REDIS_TEST_SERVER=redis
    volumes:
      - ../:/boost-redis
